### ISSUE TITLE
Allow symfony4 and symfony5?

### ISSUE THREAD

**Issue by gabiudrescu** [phpro/soap-client-sf2-bridge#9]
I would find this bridge quite useful in my Symfony4 app. are you open for a PR to make this bundle compatible with the latest Symfony version?

**Comment by veewee** [comment]
Sure thing! Feel free to provide a PR and let me know if you need help.

(BTW: I think it is fine to support SF 4.4 -> 5.X in a new version)

**Comment by janvernieuwe** [comment]
We should also consider forking it into a new repo that doesn't have a sf version in the name perhaps :|

**Comment by veewee** [comment]
We decided to discontinue support on this repo. 
The main soap-client repo contains a lot of tools already to debug soap calls in a framework independant way.

Feel free to fork this repo if you love to use it.
